### ISSUE TITLE
Improve README setup instructions

### ISSUE THREAD

**Issue by hmartos** [Adalab/easley-s4-nfq#3]
It can be obvious for experienced developers that is needed to make `npm install` before running the application with `npm start`, but I think it could be useful to add it to the README.md.

Maybe you can even add `git clone https://github.com/Adalab/easley-s4-nfq.git` in a Clone the repository section.

**Comment by claraharguindey** [comment]
Thank you @hmartos ! We improved our README and now is up to date :+1:
